### PR TITLE
Solve problems #1442

### PR DESCRIPTION
**Pull request by SouJack**
A small change to remove the dependency on the "System.Diagnostics.PerformanceCounter" package for non-Windows binary projects.
For #1442

### CODE REVIEW

**Comment by mgravell** [comment]
With the definition

``` xml
<DefineConstants Condition="'$(TargetFramework)' != 'net461' and '$(TargetFramework)' != 'net472'">$(DefineConstants);XAMARIN</DefineConstants>
```

This isn't really "am I Xamarin?", but is instead: "am I anything except .NET Framework", and since .NET Framework is only really retained for legacy convenience, it is really "am I anything?"

I would prefer to be much more selective in this issue, if possible - perhaps checking the runtime environment to isolate places where we know it will fail, rather than just assuming "not .NET Framework? it'll fail". Perhaps via one of the `RuntimeInformation` APIs?

**Comment by SouJack** [comment]
In fact, it is not really xamarin. But it has been tested and is being used at runtime. The solution can be more elaborate, I agree, but, fact that the solution for those who want to use in XF works correctly both Android and iOS. And of course it still works normally in .Net Core since the Nuget package itself does not contain the separation for xamarin runtimes.
It is a suggested course to follow for a final solution.

**Comment by SouJack** [comment]
That's correct, but by your own code and comments, if you can't get access to the object, you return false, what I did was remove it, since for Android and iOS the package doesn't exist. As I said earlier, this is only a suggestion following the logic of writing in the class in question.
For me it is working perfectly and I see that there are people with the same problem, until a definitive suggestion comes out I think it can be useful.

**Comment by mgravell** [comment]
Ultimately, the problem is that you didn't remove it for Android and iOS -
you removed it for everyone. It is frustrating, because ultimately this is
a packaging failure in an external package: it should *just work* (even if
that means it doesn't work at runtime, but in a known way), but... sigh.

**Pull request closed without merging**
