### PR TITLE
Faster byte array comparison

### PR DESCRIPTION
**Pull request by breyed**
This algorithm runs about 40% faster than the one it replaces.

### CODE REVIEW

**Comment by breyed** [comment]
This is a edit I made directly from the GitHub website. I don't know why the diff is showing massive changes. The only real change is to replace Equals with a different algorithm, copied directly from [this StackOverflow answer](http://stackoverflow.com/a/8808245/145173), with a couple variable name changes to match the original method parameter names. I tried the edit twice and got the same diffing problem each time.

**Comment by mgravell** [comment]
Github is showing 100% change there (presumably line endings). Can you
perhaps give a description of the main changes? Is it mainly the `unsafe
bool Equals(byte[] x, byte[] y)` method?

**Comment by mgravell** [comment]
Ah, sorry - your second post arrived while I was reading. Thanks - reading
now.

**Comment by mgravell** [comment]
This seems to change the logic for comparing two null arrays, which were previously considered equal - and in doing so it also omits the (essentially free) "the same array compared to itself" scenario. The latter is a nice-to-have, but the former needs fixing, IMO. I want to run my own speed comparison, out of curiosity; but yes, it is a nice way of handling those pesky last few bytes after the 64-bit comparable chunks.

**Comment by mgravell** [comment]
Concern not addressed in a year; closing

**Pull request closed without merging**
