### PR TITLE
Added SetUnion, SetIntersect and SetDiff to IDatabase. All of them are used SetCombine method

### PR DESCRIPTION
**Pull request by mohsenbgi**
Added SetUnion, SetIntersect and SetDiff to IDatabase.
All of them are used SetCombine method

### CODE REVIEW

**Comment by NickCraver** [comment]
Hey there! I'm curious what functionality is missing in the current APIs here - can you please explain what's not current covered by the `SetCombine(AndStore)(Async)` methods today?

**Comment by mohsenbgi** [comment]
Hi there, I think that if Redis commands are named intuitively, they can be easier to use and enhance the readability of the code.

**Comment by NickCraver** [comment]
I hear you, and that's certainly a good argument I agree with for any new APIs being added to be intuitive as always, but adding duplicate commands creating both confusion and a lot of overhead does not further that goal.

If we have thoughts on how to make the existing APIs more discoverable, certainly open to options there but we shouldn't add dozens of duplicates to the surface area to achieve that :)

**Comment by mohsenbgi** [comment]
You're right. Thanks for taking the time to review 🙌.

**Pull request closed without merging**
