### PR TITLE
Workaround for connecting redis via host name on Linux

### PR DESCRIPTION
**Pull request by cnblogs-dudu**
Address #410

### CODE REVIEW

**Comment by Tratcher** [comment]
Taking just the first address is not ideal. e.g. IPv6 addresses are often returned first and the server may or may not be listening on IPv6. A full replacement would loop through the returned addresses.

**Comment by cnblogs-dudu** [comment]
`addresses.FirstOrDefault(ip => ip.AddressFamily == AddressFamily.InterNetwork)` only gets IPv4 addresses.

**Comment by Tratcher** [comment]
Sure, and if there's more than one IPv4 address and the server's only listening on one?

**Comment by NickCraver** [comment]
@Tratcher do you have any thoughts on this? Is something coming in CoreFX? This is something *so many* libraries are going to have to do...it seems silly that they'll all have their own approach, doesn't it? Or am I missing something here?

**Comment by Tratcher** [comment]
@NickCraver I'm as disappointed with https://github.com/dotnet/corefx/issues/8768 as you are. https://github.com/dotnet/corefx/issues/11564 is a mediocre compromise and it doesn't look like it's coming anytime soon.

**Comment by MichaCo** [comment]
@Tratcher @NickCraver Maybe off topic, but, does that "workaround", using the IP instead, even work with Azure Redis? I tested that some time ago and couldn't make it work because you basically only have the domain name via SSL. Connecting via IP just didn't work.

**Comment by NickCraver** [comment]
This is coming back in `netstandard` itself, so I don't think we should have it in our code (the same as *every* other library would have to) - see: https://github.com/dotnet/corefx/pull/16373

Thoughts about the best interim route given all of the issues and corner cases above with IPv4, IPv6, etc.?

**Pull request closed without merging**
