### PR TITLE
Disable Stop-Words added

### PR DESCRIPTION
**Pull request by rajeshsubhankar**
An option to disable Stop-Words completely while creating schema.

### CODE REVIEW

**Comment by mgravell** [comment]
Can you please confirm that 7 is the right flag? This is UseTermOffsets | KeepFieldFlags | UseScoreIndexes.

Are you sure this shouldn't be 8?

**Comment by rajeshsubhankar** [comment]
Making it 8 will enable `NOOFFSETS`,`NOFIELDS `and `NOSCOREIDX `while someone has opted for **DisableStopWords** only.

What I assumed was, disabling stop words should not affect any other flags (here, it will not pass any other flags and let the RediSearch engine to create the schema with default configuration) .

Similarly if someone has opted for `UseTermOffsets  `or `KeepFieldFlags `, it will not enable **DisableStopWords** by default.

Please let me know if my assumption is wrong.

**Comment by mgravell** [comment]
I don't know the interplay of how these flags are meant to interact. But if you use 7, then it *absolutely* affects other flags - you cannot specify `DisableStopWords` **without** also enabling `UseTermOffsets`, `KeepFieldFlags` and `UseScoreIndexes`. It would be impossible to specify `DisableStopWords` by itself, or `DisableStopWords | UseScoreIndexes`; anything that involves `DisableStopWords` automatically includes `UseTermOffsets`, `KeepFieldFlags` and `UseScoreIndexes` .

Likewise and for the same reason: if someone has intentionally enabled `UseTermOffsets`, `KeepFieldFlags` and `UseScoreIndexes` - then with the choice of 7: they will suddenly find that `DisableStopWords` is enabled. 

If that isn't what is intended, 7 is an inappropriate choice.

**Comment by mgravell** [comment]
> Making it 8 will enable NOOFFSETS,NOFIELDSand NOSCOREIDXwhile someone has opted for DisableStopWords only.

That's surely expected? If they didn't specify `UseTermOffsets`, and *not specifying* `UseTermOffsets` means `NOOFFSETS` is added, then... that's exactly right, no?

**Comment by rajeshsubhankar** [comment]
Well, that's correct.  But `UseTermOffsets` is by default enabled in `FT.CREATE` . So, from a developer point of view making it mandatory to provide this flag so as to enable it seems little odd to me.

**Comment by rajeshsubhankar** [comment]
We can go with 8 so as to satisfy our previous flag configurations.  I will make the changes right now. Thanks.

**Comment by mgravell** [comment]
> Well, that's correct. But `UseTermOffsets` is by default enabled in `FT.CREATE` . So, from a developer point of view making it mandatory to provide this flag so as to enable it seems little odd to me.

Ultimately that was a design choice you made when you switched from opt-out flags (`NOOFFSETS`) to opt-in flags (`UseTermOffsets`).

But: if they want "defaults plus no stopwords", then: `IndexOptions.Default | IndexOptions.DisableStopWords` (and changing to `8`, obviously)

**Comment by mgravell** [comment]
k; merging; let me know if that all looks good to you - about to head out for food, but will try to build/deploy when I get back later

**Comment by rajeshsubhankar** [comment]
Looks good. Thanks.

**Pull request merged**
