### PR TITLE
Allow CheckCertificateRevocation to be set on connection string

### PR DESCRIPTION
**Pull request by lwlwalker**
This configuration setting can't be set right now using connection string. 
Usage example: 
"redishost:6380,ssl=True,checkCertificateRevocation=false"

### CODE REVIEW

**Review by mgravell — CHANGES_REQUESTED** [review]
Missing inclusion when *generating* a string - see `public string ToString(bool includePassword)` - and should probably be a test for that (perhaps just test the output of `options.ToString()` in `ConfigurationOption_CheckCertificateRevocation`?) - but otherwise: looks great, thanks!

**Comment by lwlwalker** [comment]
ToString functionality added and unit-tested

**Review by mgravell — APPROVED** [review]

**Comment by mgravell** [comment]
Looks fine, thanks. I'll pull it locally before merging, but: 👍

**Comment by NickCraver** [comment]
Merging main in here to get build checks decent

**Comment by lwlwalker** [comment]
Hi @mgravell , @NickCraver , 

Any news on this? I don't know why the build fails, as my changes are not related to the errors there (I think 8-D), and I created my Fork from master...

Please, let me know if I can help here somehow...

**Comment by mgravell** [comment]
@lwlwalker  I'm not concerned about the unrelated build failures - I just haven't had time to revisit for a build/merge session

**Comment by mgravell** [comment]
merged with thanks

**Pull request merged**
