### PR TITLE
.netstandard2.0 use APM reduce timeout exception.

### PR DESCRIPTION
**Pull request by majian159**
#678

### CODE REVIEW

**Comment by majian159** [comment]
This is not valid in linux

**Comment by NickCraver** [comment]
We need a little more information here, I'm still not sure what we're looking at. What is the goal we're trying to fix? The `netstandard2.0` setup in general will need a different approach, I recommend we look at whatever the intended functionality here is after that merge (I'm working on getting Sentinel in first).

**Comment by zhouqi6876** [comment]
@majian159  Do you known how to solve the timeout exception with .net core in linux？

**Comment by majian159** [comment]
@zhouqi6876 
https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Timeouts.md
In .Net Core, add Environment Variable COMPlus_ThreadPool_ForceMinWorkerThreads to overwrite default MinThreads setting, according to Environment/Registry Configuration Knobs

**Comment by zhouqi6876** [comment]
@majian159 I try to export ComPlus_ThreadPool_ForceMinWorkerThreads=50, it doesn't work ,have you ever tried？

**Comment by majian159** [comment]
@zhouqi6876 can refer to https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/specs/runtime-configuration-file.md.

**Comment by wjdavis5** [comment]
@majian159 
You can also use the SetMinWorkers() method as documented here:

https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.setminthreads?view=netstandard-2.0

**Comment by NickCraver** [comment]
The next build will have `netstandard2.0` in it - I'm closing this one out as there's no update or information on how it relates really. The commit here introduces another package entirely which doesn't include support for TwemProxy (which isn't enabled by default anyway)...I'm not sure what condition this would make sense. Happy to discuss further, but we need more info.

**Pull request closed without merging**
