### PR TITLE
WIP: Rebased on master: Sentinel Support + Test system modernisation

### PR DESCRIPTION
**Pull request by haf**
# WIP:

 - [x] Set up Minikube environment
 - [x] Run redis-server
 - [x] Set up [my own travis build](https://travis-ci.org/haf/StackExchange.Redis)
 - [ ] Run redis-server <conf> --sentinel
 - [ ] Ensure failover when killing off pods is working
 - [ ] Make tests pass
 - [x] Document minikube/testing setup
 - [ ] Ping maintainers

@mgravell @NickCraver — what tests are expected to pass and which ones to fail? Just so I know the baseline I start from here?

### My considerations and aims

 - Strong names or not? (assume we can remove)
 - Redis v4.0 not v3.x
 - I don't have much time to do this PR, so when I don't get feedback (e.g. on the above) I will choose a path myself. Time span I have to do this is 1-2 full time days.

### Env with redis

    brew cask install virtualbox
    # https://github.com/kubernetes/minikube/releases
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.25.0/minikube-darwin-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
    minikube start
    # clone this repo
    cd tests
    ./1.create-resources
    # wait until the stateful sets are up
    ./2.replicate-redis
    # => OK, OK
    k get svc
    # => redis-testing   NodePort    10.105.115.238   <none>        6379:30814/TCP,16379:31723/TCP   5m
    # This tells you where to access it.

### Env with code

    source .env
    dotnet restore
    dotnet build --framework=netstandard2.0 StackExchange.Redis/StackExchange.Redis.csproj

### Sentinel

https://redis.io/topics/sentinel

# See #692 - this is just a rebase and not my work:

Initial pass at adding Sentinel support. Adds ConnectionMultiplexer that
is managed by a set of Sentinel servers. Usage:
```C#
ConfigurationOptions sentinelConfig = new ConfigurationOptions();
sentinelConfig.ServiceName = "ServiceNameValue";
sentinelConfig.EndPoints.Add("127.0.0.1", 26379);
sentinelConfig.EndPoints.Add("127.0.0.2", 26379);
sentinelConfig.EndPoints.Add("127.0.0.4", 26379);
sentinelConfig.TieBreaker = "";
sentinelConfig.DefaultVersion = new Version(3, 0);

// Add the configuration for the masters that we will connect to
ConfigurationOptions masterConfig = new ConfigurationOptions();
sentinelConfig.SentinelMasterConfignfigurationOptions = mo;

// Connect!
ConnectionMultiplexer sentinelConnection =
ConnectionMultiplexer.Connect(sentinelConfig);

// When we need to perform a command against the masters, use the master
connection
sentinelConnection.SentinelMasterConnection.GetDatabase().MyCommand();
```

Sentinel Support - Second Draft

Modified approach to allow for a sentinel-only setup with the option of
requesting a connection to a master managed by the sentinel connection.
Can also support multiple services on the same sentinel.

Handle closed managed connections

Add some basic handling for disposed connections that are managed by the
Sentinel connection.

### CODE REVIEW

**Comment by NickCraver** [comment]
@haf This is really a lot of PRs tied into one. I'm not opposed to a Travis build for this, but a lot of things are happening all at the same time:
- Dropping net45 support (arguably breaking...but we're considering this anyway)
- Adding a whole net build system
- Adding Sentinel support

These should be broken out. I'm currently working on getting *all* tests to pass on Appveyor, but there's an xUnit issue in play they just merged in yesterday I'm hoping resolves the downtarget resolution to `netcoreapp1.0`. Sentinel's main problem is no testing to ensure it works at all (this is still a pending issue on the PR), so Sentinel support + tests should be an individual PR. Adding Travis builds is another, but I'm not sure we'll be on Appveyor/Travis long-term due to stability problems with the agents and I want to be 100% up front about that before significant effort is expended here.

Lastly, as part of the cleanup and sockets rewrite we want to ensure Mono works with the same lib, and I'm not 100% sure what that looks like yet. We're not consumers of Mono and need to setup environments to work on it in. I hope that doesn't affect the build much, but it may.

**Comment by haf** [comment]
> This is really a lot of PRs tied into one. I'm not opposed to a Travis build for this

Good, because that's going on on my side of things. It can be removed once LGTM is reached.


> Dropping net45 support (arguably breaking...but we're considering this anyway)

Right, but it has to compile cross platform for me; in the end, this can be worked around, but if it gates the PR it can be reverted. Let's discuss that when this is ready to be merged. Right?

> Adding a whole net build system

I removed that.

> Adding Sentinel support

What the PR is about.

> These should be broken out.

See changed above.

> I'm currently working on getting all tests to pass on Appveyor, but there's an xUnit issue in play they just merged in yesterday I'm hoping resolves the downtarget resolution to netcoreapp1.0.

+1 nice, but please don't gate PRs on that. Instead skip the failing tests, make the CI green and let people cooperate on those tests that are working.

> Sentinel's main problem is no testing to ensure it works at all (this is still a pending issue on the PR), so Sentinel support + tests should be an individual PR.

Again, that's this PR.

> Adding Travis builds is another, but I'm not sure we'll be on Appveyor/Travis long-term due to stability problems with the agents and I want to be 100% up front about that before significant effort is expended here.

Yes, gotcha. No significant effort has been spent and I won't spent that either. I'll use a mitmproxy or something in kube as a side-car and test it that way. I'd also happily write some model-based property tests with Expecto if you can stomach F#.

> Lastly, as part of the cleanup and sockets rewrite we want to ensure Mono works with the same lib, and I'm not 100% sure what that looks like yet.

Please don't gate this PR on future work?

> We're not consumers of Mono and need to setup environments to work on it in. I hope that doesn't affect the build much, but it may.

I've pushed a minikube environment; I'll ensure it can run the tests in mono as well, so don't spend time on this. However, it's better to have a client that doesn't support mono but supports .net core cross platform, than it is to delay releases and PRs waiting for mono to happen, IMO. So please consider not gating anything on mono nor the future work and we'll continue improving and taking it forward.

**Comment by haf** [comment]
https://travis-ci.org/haf/StackExchange.Redis

**Comment by NickCraver** [comment]
> Right, but it has to compile cross platform for me; in the end, this can be worked around, but if it gates the PR it can be reverted. Let's discuss that when this is ready to be merged. Right

We don't need it to compile cross-platform. We only need to *build* it once. It should *run* cross-platform. We are a library and need to be keenly aware those concerns are separate.

> I removed that.

It's still *most* of this PR - I don't see anything removed.

> +1 nice, but please don't gate PRs on that. Instead skip the failing tests, make the CI green and let people cooperate on those tests that are working.

It's not a set of tests that are failing, it's the build, concurrency, and load that cause *different* sets of tests to fail. Only one it a known failure. I will not be skipping and ignoring the issues, that's why I'm working on them at night now. We want to get 1 build green (**consistently** green and predictable) before adding another.

> Please don't gate this PR on future work?

This cleanup is happening **now**, not in the future. Pretending that things like this don't have weight is not an argument I'm going to have. They do. It adds a build that will be failing. We don't want to deal with that until we are stable to begin with.

> I've pushed a minikube environment; I'll ensure it can run the tests in mono as well, so don't spend time on this. However, it's better to have a client that doesn't support mono but supports .net core cross platform, than it is to delay releases and PRs waiting for mono to happen, IMO. So please consider not gating anything on mono nor the future work and we'll continue improving and taking it forward.

We already have that. This doesn't enhance the multi-platform at all.

Again, adding a build system and Sentinel should be separate PRs. We're changing the build system completely in a few months and I'm not sure Travis will ever make sense here in our long-term plans.

**Comment by haf** [comment]
No, I haven't replaced the build system. What are you referring to???

**Comment by NickCraver** [comment]
@haf I'm sorry you feel that way. 29 of 34 files here are around the build and test running, *not* the Sentinel addition. These should be separate PRs for pretty much any project out there. I don't personally feel this is unclear to anyone looking. While I'd love to get Sentinel support in and support other builds once we get the first working, a take-it-all-or-nothing approach is not productive. There are costs and conflicts with many changes and this disrupts work currently in progress. If you feel this can't wait *at all* then yes, we're better off closing it out.

I'm actively trying to get a consistent build working so that we can take contributions much easier, but nothing is instant and we aren't paid to work on this - it's time we allocate as much as we are able (including many dependencies *underneath* this currently in play). I hope to get the build green over the next few days but Appveyor has it's own stability issues with the size agents they use. Hence, we may not be on it long-term and while I know what we'll probably move to can support our current build, I have no idea if it'll support everything setup here. We're more likely to have a mostly shared build across platforms if needed, rather than `n` large build bootstraps at 1 per platform.

**Comment by haf** [comment]
@NickCraver I understand where you are coming from and that fixing outstanding issues that indicate core problems with this library are more important. I fully support that.

In the light of the Sentinel PR from August never having been merged and often gone without reply, I thought I'd rebase it for you. So the sentinel PR already stands on its own with our without my minor contribution to it.

I read through most other PRs as well and they are often stalling based on your ability to spend time. So I was thinking I could help you out.

I've tried the sending of multiple PRs before and that almost never works out, because it often leads to one being merged and all others then being conflicting/unmergeable. Also, sending more PRs more often leads to more back and forth which I can't spend the time to do, as I'm on a deadline.

So given that the sentinel PR is already stand alone (the merge was a single line that had been identically refactored by both yourself and the author), I wanted to help you with a setup that you can test on; that's this PR as it stands right now. I don't believe in running Linux services on NTFS and Windows Server, so I set up the infra you need to run Linux services virtually on Windows hosts. As far as I can see, that's an improvement on the state of things. Generally; test against what you'll run in production.

So when I get replied to like "Pretending that things like this don't have weight is not an argument I'm going to have." it feels like you're overly aggressive. Also, stating that you don't care about compiling cross platform, when I obviously do is also a bit passive aggressive to others, since it precludes their contributions. I've run OSS for years on .Net and generally a build toolchain can be set up for both; the very least compiling, if not QA/testing, without too much hustle.

**Pull request closed without merging**
