### PR TITLE
Add geo add

### PR DESCRIPTION
**Pull request by wjdavis5**
I've went through and made most of the suggested changes, I didnt remove the geo radius member yet. I'm trying to remember what I was thinking at the time I put it in there. Nonetheless comments are welcome as always. 

I'm hoping to get this finished up sometime in the near future.

### CODE REVIEW

**Comment by wjdavis5** [comment]
Also, I'm not real sure why Appveyor is having a hard time with the build, as I'm not able to reproduce this behavior locally...

**Comment by Wallonman** [comment]
Hi,

I'd like to participate to this request. First of all we've installed Redis 3.2 to get the new GEO features, and we're using your great library. Therefore we'd like to get them in the master as soon as possible.

What is your road map to merge this request into the master ?

In the meanwhile we made some tests, and we found an issue with one parameter (COUNT) in the GEORADIUS command.
So what is the procedure to help you fixing that issue ?
Should I create a branch ?

Another question raise here : till the branch is not merged to the master, we'd like to produce our own local nugget package, so can you tell me some clue to create that package ? Do you have any script or do you that manually ?

Regards,

Eric

**Comment by mgravell** [comment]
Well this is awkward... I've recently pulled this into a branch and have
been working through some of the changes (and using it as a baseline for
the changes we need for modules). I ... don't know the right way to head
now, but we're in for a world of merge pain either way...

**Comment by wjdavis5** [comment]
Not sure where the pain lies but I'm could lend a hand if it would be useful.

**Comment by Wallonman** [comment]
Hi guys,

Looking into this compilation issue, I've found what's wrong. There are missing files.
The appveyor tells us that:
`CSC : error CS2001: Source file 'C:\projects\stackexchange-redis\StackExchange.Redis_Net45\..\StackExchange.Redis\StackExchange\Redis\Compat\BufferedOutputStream.cs' could not be found. [C:\projects\stackexchange-redis\StackExchange.Redis_Net45\StackExchange.Redis_Net45.csproj]`

Look at this screen shot, the file is missing in commit bc2ec48  
image


The file was removed on commit : https://github.com/StackExchange/StackExchange.Redis/commit/bc2ec482dacb707ec0ec2b8578bf6988b22d9837

Hope that helps,

Eric

**Comment by NickCraver** [comment]
@Wallonman Indeed - unfortunately for some reason this PR makes massive changes to the `.csproj` files, explicitly referencing all `.cs` files individually instead of the glob includes that were there. We also don't build with these project systems anymore. 

I expect we should probably upgrade to the VS 2017 format in the next RC. It's coming along just not quite there for stable projects yet. The issue is that it excludes contributors without VS 2017 from working...it's a sharp cutover that's not at all open source friendly. However, it avoids most to all of the project file conflicts like this.

**Comment by Wallonman** [comment]
I've pushed the fix on my branch : https://github.com/Wallonman/StackExchange.Redis

Someone can try to build on the CI ?

**Comment by wjdavis5** [comment]
@NickCraver  - I cant really speak as to why the file refs changed. It isnt something I specifically recall doing, nor do I know why I would have had a reason to. I do recall it giving me headaches when I added in new files though. Perhaps something I did when adding new files caused a problem.

**Comment by Wallonman** [comment]
When saving the project with VS 2013 then the csproj is modified and the
wildcard is replaced by the list of files included in the projet.

This should not be an issue, you just must take care to - when you add or
remove files from the projet - commit the added/removed file to git in
order to be synced

____________________
Eric Piraux
+32 476 20 29 60

2016-12-29 20:18 GMT+01:00 William Davis <notifications@github.com>:

**Comment by mgravell** [comment]
Having a look through now; note - unless I hit a brick wall, I'll try to make any fixes myself locally - any comments will be purely informational unless indicated otherwise; will add them here to track (because the review is already hella confusing)

So far:

- `GeoEntry` - `.Member` should be `RedisValue`
- `GeoAdd` - should either take `GeoPosition`, or if taking `GeoEntry` there is no need for `member`, since `GeoEntry` includes `.Member`

**Comment by mgravell** [comment]
my changes are visible in this branch (until I delete it) for your reference; https://github.com/StackExchange/StackExchange.Redis/commits/wjdavis5-AddGeoAdd

so far I've only looked at the code; putting it through its paces shortly. Thanks for the PR - much appreciated. Sorry it has taken some time and some iteration, but I'm ... fussy. More specifically, it is virtually impossible to fix any API problems once we've released them, so it needs to be "right enough" first time out of the gate.

**Comment by mgravell** [comment]
woohoo; tests added for all methods, and merged; thanks for the contribution

**Comment by mgravell** [comment]
https://www.nuget.org/packages/StackExchange.Redis/1.2.0-alpha1

**Pull request merged**
