### PR TITLE
Proxy: move to extension methods

### PR DESCRIPTION
**Pull request by NickCraver**
This should make PRs like #1977 and #1425 much easier.

### CODE REVIEW

**Comment by NickCraver** [comment]
@rkarthick I really just want a second set of eyes on this, if you have time to review happy to get it in and unblock ya!

**Review by rkarthick — APPROVED** [review]
LGTM. 

Do we need to modify this:
https://github.com/StackExchange/StackExchange.Redis/blob/80701beb315b30ade972a4cc2d7cf6c6862bee8c/src/StackExchange.Redis/ServerEndPoint.cs#L331
to
`if (!serverType.SupportsAutoConfigure())`

**Comment by NickCraver** [comment]
@rkarthick Indeed! Missed a file in the branch do-over here, thanks!

**Review by rkarthick — APPROVED** [review]
+2

**Comment by NickCraver** [comment]
@rkarthick thanks again for taking a poke here and helping us improve - a PR against `main` should be _much_ more friendly not - can open a new PR or just force push the other!

**Comment by rkarthick** [comment]
this is great, ty @NickCraver I will open a new PR over `main` and will send it out later today.

**Pull request merged**
