### PR TITLE
Implement api for rpushx/lpushx with multiple values

### PR DESCRIPTION
**Pull request by dmytrohridin**
Issue: https://github.com/StackExchange/StackExchange.Redis/issues/1450
Add methods for rpushx/lpushx with multiple values
Do not delete old to save backward compatibility

### CODE REVIEW

**Comment by mgravell** [comment]
This is looking really good, very nice job. I especially like the use of `LLEN` when there are zero elements, to preserve the result semantics.

IMO there's still a little bit missing here - specifically some integration tests that show it actually working on a real server (I see some unit tests checking the wrapper, that's great, thanks). In particular, I'd like to see validation of the behaviour of (cross-joined):

- zero vs one vs many items added
- "when" usage with key exists vs key doesn't exist

**Comment by dmytrohridin** [comment]
Got it. Will add tests today later

**Comment by dmytrohridin** [comment]
@mgravell added more tests :)

**Review by mgravell — APPROVED** [review]

**Comment by mgravell** [comment]
merged, thanks

**Pull request merged**
