### PR TITLE
Obsolete label for responseTimeout and writeBuffer in docs

### LINKED ISSUE #1490: Obsolete responseTimeout in docs
ResponseTimeout is marked as obsolete and is not in use anymore, but it is not obvious from [docs](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Configuration.md). It was bit confusing to me, because I was using it as connectionString parameter and haven't seen any warnings. What do you think of marking it as obsolete in docs (or even remove it from docs)?

### PR DESCRIPTION
**Pull request by suslovk**
Resolves #1490

### CODE REVIEW

**Comment by suslovk** [comment]
Cool, it looks better after separation. I have seen you tweet, that docs are rendered from master branch, not main for now. Do you want me to make a request to master branch cherry-picking those changes?

**Comment by NickCraver** [comment]
Oh, right! Good call - I pushed it over there :) Thanks again!

**Comment by suslovk** [comment]
I'm very sorry for taking your time on such a small feature, but there is one more thing to do there. Although github [renders it correctly](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Configuration.md#obsolete-configuration-options), github pages [fails to render](https://stackexchange.github.io/StackExchange.Redis/Configuration#obsolete-configuration-options) new version. I've found an [issue](https://github.community/t/md-to-html-conversion-does-not-seem-to-work-properly/10435), that github and github pages use different render engines and tried to make it works on both. It turned out that github pages needs blank line before table to be rendered correctly. I've [tried](https://github.com/suslovk/StackExchange.Redis/commit/9ff8aeaae3d33e8e6dd5c6741c8c232754c4c547) it and it [works as expected](https://suslovk.github.io/StackExchange.Redis/Configuration#obsolete-configuration-options). Do you want me to make a PR?

**Comment by NickCraver** [comment]
@suslovk no bother at all - thanks a ton for the follow-up! TIL there's a preview difference...wasn't aware of that. Newline pushed up :)

**Pull request merged**
