### PR TITLE
Added support for subscribe-to-slave...

### PR DESCRIPTION
**Pull request by mckenzieg1**
...by making Subscription.SubscribeToServer() use passed-in CommandFlags for server selection. [Fixes StackExchange/StackExchange.Redis#137]

Included a pair of unit tests that highlight the underlying issue and the broken behavior (subscription to slave-only configurations don't work at all).

### CODE REVIEW

**Comment by NickCraver** [comment]
IMO this makes sense - can you please rebase the changes?

**Comment by mckenzieg1** [comment]
@NickCraver - sure. This one got caught in limbo between Marc Gravell's and my back-to-back vacations. I have since handed off Redis-related stuff to another developer at my company - I will let him know that if we fix up the PR we can probably get it accepted soon.

**Comment by NickCraver** [comment]
See discussion in #321 - we'll have to address the tracking a well, so a bit more complicated that it initially appears here.

**Comment by mckenzieg1** [comment]
@NickCraver - understood. We have started using 'subscribe to slave' more extensively in our system recently (with our fork of the library including my change). I haven't been working on that aspect lately - I will ask my colleague who is the current expert what he has been seeing and what he thinks about re-connection scenarios specifically. If he comes up with some more fixes we will submit them.

**Comment by NickCraver** [comment]
@mckenzieg1 I need to cleanup here for a VS 2017 migration. I'm not ignoring this issue - we'll track it in #321, but I need to get PRs either merged or cleared for this migration and we need to think through this much deeper and address re-subscribes...so the final PR will look very different anyway.

Note: there's also a related async issue for callers off the subscription that may or may not have a related solution.

**Comment by mckenzieg1** [comment]
@NickCraver Understood - no problem.

**Pull request closed without merging**
