### PR TITLE
Adding Profiling Interfaces

### PR DESCRIPTION
**Pull request by kevin-montrose**
This is a squashed version (+1 merge with master) of [this branch](https://github.com/kevin-montrose/StackExchange.Redis/tree/profiling).

This adds the following to the public interface:

 - [`ConnectionMultiplexer.RegisterProfiler(IProfiler)`](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.Profiling.cs#L25)
   * Restriction: This method can only be called once on a ConnectionMultiplexer instance
 - [`ConnectionMultiplexer.BeginProfiling(object)`](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.Profiling.cs#L44)
   * Restriction: The [`WeakReference` class](https://msdn.microsoft.com/en-us/library/system.weakreference%28v=vs.110%29.aspx) cannot be used as a context object.  This restriction makes some leak detection code simpler, and it's somewhat non-sensical to provide a weak context anyway, so I think this is an acceptable restriction.
 - [`ConnectionMultiplexer.FinishProfiling(object, bool)`](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.Profiling.cs#L61)
 - The [`IProfiler` interface](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/IProfiler.cs#L113)
 - The [`IProfiledCommand` interface](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/IProfiler.cs#L30)
 - The [`RetransmissionReasonType` enum](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/IProfiler.cs#L17)
 - The [`ProfiledCommandEnumerable` struct](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ConcurrentProfileStorageCollection.cs#L20)

Consumer use is outlined in [new documentation](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/Docs/Profiling.md), and demonstrated in [new tests](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis.Tests/Profiling.cs#L13).

----

## Implementation Details

Care was taken to make this a low impact and safe change.  No calls to consumer provided code occur on any worker threads to avoid thread stealing (this is why the `IProfiler` interface is not a collection of callbacks).  There is a single call to [`IProfiler.GetContext()`](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs#L1645), which always occurs on the thread of a consumer calling into a `ConnectionMultiplexer`.

The task of tracking the various contexts in flight is handled by the [`ProfileContextTracker` class](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ProfileContextTracker.cs#L14).  Conceptually it is a wrapper around a `ConcurrentDictionary<Key, Value>`, which supports periodic sweeps to cleanup contexts that are no longer reachable.  Determining when a context has  been "leaked" is handled by the [`ProfileContextCell` struct](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ProfileContextTracker.cs#L26).  By default a sweep is executed once a minute, but this can be disabled via the [`allowCleanupSweep` parameter on `ConnectionMultiplexer.FinishProfiling(object, bool)`](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.Profiling.cs#L61).  A [test for cleaning up leaks](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis.Tests/Profiling.cs#L302) is also a part of this pull request.

The collection used to group related commands together is the custom [`ConcurrentProfileStorageCollection` class](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ConcurrentProfileStorageCollection.cs).  It only supports adding elements and enumerating, with creating an enumerable object implicitly disabling future adds.  [Addition is, naturally, thread-safe](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ConcurrentProfileStorageCollection.cs#L167) while [creating an enumerable is not](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ConcurrentProfileStorageCollection.cs#L191) (since a single call to `ConnectionMultiplexer.FinishProfiling(object, bool)` is the only thing that can cause enumerable creation).

`ConcurrentProfileStorageCollection` is an [intrusive](http://stackoverflow.com/q/5004162/80572) singly linked list of [`ProfileStorage` classes](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ProfileStorage.cs).  This behavior, in combination with pooling `ConcurrentProfileStorageCollection`s, keeps allocations relatively low (typically 1 allocation per `Message` sent while profiling).

`ConnectionMultiplexer.FinishProfiling(object, bool)` returns a [`ProfiledCommandEnumerable` struct](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ConcurrentProfileStorageCollection.cs#L20) so that `GetEnumerator()` calls can be allocation free, in a similar fashion to `List<T>` and `Dictionary<T,V>`.

Cluster complicates thing slightly, with MOVED and ASK responses.  In the [resend case](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/ServerSelectionStrategy.cs#L154) a new `ProfileStorage` instance is created and replaces the one originally attached to the `Message` being reused.  The original `ProfileStorage` instance is still recorded, and the new one references the original via the [`IProfiledCommand.RetransmissionOf`](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/IProfiler.cs#L99) property.  Consumer code is not called multiple times in this case, the `ProfileStorage` is associated with the same context automatically.  There is [a test for this behavior](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis.Tests/Cluster.cs#L583) as well.

[`Message` grows three additional fields in this pull request](https://github.com/kevin-montrose/StackExchange.Redis/blob/profiling-squashed-v4/StackExchange.Redis/StackExchange/Redis/Message.cs#L151), two timing values and one reference to a `ProfiledStorage` instance.  The `SetProfileStorage(ProfileStorage)`, `PrepareToResend(ServerEndPoint, bool)`, `SetResponseReceived()`, `SetEnqueued()`, and `SetRequestSent()` methods are all also added to `Message`.  Calls to these new methods are inserted into the appropriate places in `ConnectionMultiplexer`.

### CODE REVIEW

**Comment by mgravell** [comment]
k, I'm confused; in every way I can see: I've merged this - see https://github.com/StackExchange/StackExchange.Redis/commit/f5fe0e453b1ade879aac0625f62687d965a5ecae; github, however, disagrees; I followd the dreaded "Use the commmand line", but: he no workee. I can try hard to figure out what the hell git is doing to merge with full credit, or I can "Close". Views?

**Comment by kevin-montrose** [comment]
@mgravell close it.  I don't care about the PR being marked "merged," so long as the code's in.

**Comment by KyleGobel** [comment]
Hey, I couldn't find anywhere specifying when/how often you release or update, but was curious of the timeline of getting this up onto nuget?

**Comment by mgravell** [comment]
Thanks for the nudge. Will deploy asap

**Pull request closed without merging**
