### PR TITLE
Use GlobalPackageReference for Microsoft.NETFramework.ReferenceAssemblies

### PR DESCRIPTION
**Pull request by WeihanLi**
use `GlobalPackageReference` since it's for all projects and `PrivateAssets="All"`

https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management#global-package-references

### CODE REVIEW

**Comment by mgravell** [comment]
Not sure I see the benefit of this - it doesn't reduce any duplication, and the existing code is perfectly clear. It seems to be a change for change's sake?

**Comment by WeihanLi** [comment]
We can have version and reference defined in one place, without splitting into two places with this

**Comment by mgravell** [comment]
> We can have version and reference defined in one place, without splitting into two places

Which is how literally every other reference works. I'm not sure I see the benefit of changing it, honestly, other than "just because"

**Comment by WeihanLi** [comment]
I'm fine with it either way, thanks for the opinion

**Pull request closed without merging**
