### PR TITLE
Updated StreamCreateConsumerGroup methods to use the MKSTREAM option.

### PR DESCRIPTION
**Pull request by ttingen**
Added the `createStream` parameter to the `StreamCreateConsumerGroup` methods, the parameter defaults to `true`. Also added appropriate tests for the new parameter and its potential values.

### CODE REVIEW

**Comment by mgravell** [comment]
As with #1154, this needs to be done as an overload

**Comment by ttingen** [comment]
@mgravell, this PR has been updated with an overload as well. Thanks Marc.

**Comment by TheAngryByrd** [comment]
Any thing I can do to help here?

**Comment by mgravell** [comment]
merging, thanks

**Pull request merged**
