### PR TITLE
Support LCS

### PR DESCRIPTION
**Pull request by Avital-Fine**
https://redis.io/commands/lcs/

#2055

### CODE REVIEW

**Comment by Avital-Fine** [comment]
@NickCraver Hey!
I'm having problems with the PublicAPI declarations. Can you help? :pray:

**Comment by slorello89** [comment]
@Avital-Fine, fixed the API declarations

**Comment by NickCraver** [comment]
@Avital-Fine I gave this some tidy love this morning, but gotta change gears a lot today. I think at the moment all this needs is more testing around missing key cases (1 or both) and non-matches.

**Review by NickCraver — APPROVED** [review]
Current looks good - thanks for iterating on this crazy command :)

**Pull request merged**
