### PR TITLE
URGENT Fix error in batch/transaction handling

### PR DESCRIPTION
**Pull request by mgravell**
A missing API override in `RedisBatch`/`RedisTransaction` can lead to some operations **NOT ENTERING THE BATCH/TRANSACTION**. This is very bad.

Some undefined set of operations (including at least `ZRANGE`) end up using what appears to be a new overload/path; this API was not overridden in the batch/transaction, with the impact that affected operations use the default behaviour and go directly to the multiplexer/connection. This means a: they are issued even if the transaction/batch *is not ever executed*, and b: if everything is issued, they are issued out-of-order (i.e. before the main batch/transaction)

See: #2167, #2176

### CODE REVIEW

**Review by NickCraver — APPROVED** [review]
Current looks good, but I've also committed - needs cross-check eyes.

**Comment by mgravell** [comment]
Random thought; do both methods need to be virtual? Should we devirtualize the method that doesn't take the default value? One fewer thing to remember.

**Comment by NickCraver** [comment]
hmm not sure I follow (in text-only atm) - aren't we overriding it in Batch/Transaction both?

**Comment by mgravell** [comment]
> hmm not sure I follow (in text-only atm) - aren't we overriding it in Batch/Transaction both?

I'm saying "what if there was only one method to override"

**Pull request merged**
